language: python

python:
  - 3.5
  - 3.4
  - 3.3

env:
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.8,<1.9"

install:
  - pip install -U coverage coveralls django-bitfield $DJANGO

script: coverage run -a --source=standin standin/tests.py

matrix:

  exclude:

after_success:
  coveralls

